[package]
name = "raptor-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["tls", "json"] }
actix = "0.11.0"
actix-rt = "2.2"

[dependencies.pyo3]
version = "0.21.2"
features = ["auto-initialize"]